window.RECIPES = [
  {
    slug: "steak-hasselback",
    title: "Steak and Hasselback Potatoes",
    description: "A plated dinner that feels elevated without asking for restaurant-level technique.",
    category: "Dinner",
    cuisine: "American",
    difficulty: "Intermediate",
    dietaryTags: ["High-Protein", "Gluten-Free"],
    featured: true,
    popularScore: 92,
    addedOn: "2026-02-18",
    prepMinutes: 20,
    cookMinutes: 80,
    servings: 1,
    image: "Photos/Steak_Hasselback.webp",
    imageAlt: "Steak served with hasselback potatoes.",
    heroTone: "charcoal",
    ingredients: [
      "1 russet potato",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "Kosher salt",
      "1 steak",
      "Black pepper",
      "Montreal steak seasoning"
    ],
    instructions: [
      "Preheat the oven to 425 degrees Fahrenheit.",
      "Wash and dry the potato, then place it between two chopsticks or butter knives to protect the base while slicing.",
      "Cut the potato crosswise into thin slices without cutting all the way through.",
      "Melt the butter, then combine it with olive oil and salt.",
      "Brush the butter mixture over the potato, making sure it gets between the slices.",
      "Bake for 1 hour and 20 minutes, brushing with more butter mixture every 20 minutes.",
      "During the last 20 minutes, heat a skillet over medium-high heat.",
      "Season the steak on both sides with salt, pepper, and Montreal steak seasoning.",
      "Sear the steak until it reaches your preferred doneness, then rest it for 5 minutes.",
      "Plate the steak with the potato and serve immediately."
    ],
    nutrition: {
      calories: "780",
      protein: "48g",
      carbs: "34g",
      fat: "46g"
    }
  },
  {
    slug: "american-cheeseburger",
    title: "American Cheeseburger",
    description: "A classic backyard-style burger built around simple seasoning and a reliable sear.",
    category: "Comfort Food",
    cuisine: "American",
    difficulty: "Beginner",
    dietaryTags: ["High-Protein"],
    featured: true,
    popularScore: 89,
    addedOn: "2026-02-27",
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 4,
    image: "Photos/burger.jpg",
    imageAlt: "American cheeseburger with lettuce and tomato.",
    heroTone: "amber",
    ingredients: [
      "2 pounds 80/20 ground beef",
      "Salt, pepper, or burger seasoning blend",
      "4 slices cheese",
      "4 hamburger buns",
      "Lettuce, tomato, and onion",
      "Condiments of choice"
    ],
    instructions: [
      "Preheat a grill or grill pan to medium-high heat.",
      "Divide the beef into four equal portions and shape into patties.",
      "Create a small indentation in the center of each patty to help it cook evenly.",
      "Season both sides with burger seasoning or salt and pepper.",
      "Cook for 3 to 5 minutes per side, depending on thickness and preferred doneness.",
      "Add cheese during the last minute so it melts over the patties.",
      "Toast the buns if you want more texture and structure.",
      "Build the burgers with condiments, vegetables, and the hot patties.",
      "Serve immediately with your preferred side."
    ],
    nutrition: {
      calories: "640",
      protein: "36g",
      carbs: "32g",
      fat: "38g"
    }
  },
  {
    slug: "apple-crisp",
    title: "Apple Crisp",
    description: "Warm apples, cinnamon, oats, and a crisp topping that holds its texture beautifully.",
    category: "Dessert",
    cuisine: "American",
    difficulty: "Beginner",
    dietaryTags: ["Vegetarian"],
    featured: true,
    popularScore: 84,
    addedOn: "2026-01-22",
    prepMinutes: 20,
    cookMinutes: 55,
    servings: 16,
    image: "Photos/Apple-Crisp-197.jpg",
    imageAlt: "Apple crisp dessert with vanilla ice cream.",
    heroTone: "berry",
    ingredients: [
      "10 to 11 cups sliced tart apples",
      "1/2 cup sugar",
      "1 teaspoon cinnamon, divided",
      "1 cup flour",
      "1 cup brown sugar",
      "1/2 cup oats",
      "1 teaspoon baking powder",
      "1/4 teaspoon nutmeg",
      "1/2 cup cold butter",
      "Vanilla ice cream, optional"
    ],
    instructions: [
      "Preheat the oven to 375 degrees Fahrenheit.",
      "Toss the apples with sugar and half of the cinnamon.",
      "Transfer the apples to a greased 13x9-inch baking dish.",
      "In a separate bowl, combine flour, brown sugar, oats, baking powder, nutmeg, and the remaining cinnamon.",
      "Cut in the butter until the topping resembles coarse crumbs.",
      "Sprinkle the topping evenly over the apples.",
      "Bake for 50 to 60 minutes, until the apples are tender and the top is deeply golden.",
      "Serve warm, ideally with vanilla ice cream."
    ],
    nutrition: {
      calories: "330",
      protein: "3g",
      carbs: "54g",
      fat: "12g"
    }
  },
  {
    slug: "philly-cheesesteak",
    title: "Philly Cheesesteak",
    description: "A savory sandwich layered with seasoned sirloin, peppers, onions, and melted Swiss cheese.",
    category: "Sandwiches",
    cuisine: "American",
    difficulty: "Intermediate",
    dietaryTags: ["High-Protein"],
    featured: false,
    popularScore: 81,
    addedOn: "2026-02-01",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    image: "Photos/cheestesteak.jpg",
    imageAlt: "Philly cheesesteak sandwich.",
    heroTone: "charcoal",
    ingredients: [
      "1/2 teaspoon salt",
      "1/2 teaspoon black pepper",
      "1/2 teaspoon paprika",
      "1/2 teaspoon chili powder",
      "1/2 teaspoon onion powder",
      "1/2 teaspoon garlic powder",
      "1/2 teaspoon dried thyme",
      "1/2 teaspoon dried basil",
      "1 pound sliced sirloin",
      "3 tablespoons olive oil",
      "1 onion",
      "1 green bell pepper",
      "3 ounces Swiss cheese",
      "4 hoagie rolls"
    ],
    instructions: [
      "Mix the dry seasonings together in a small bowl.",
      "Slice the onion and green pepper.",
      "Toss the steak with the seasoning blend and olive oil.",
      "Heat a skillet over medium-high heat and cook the steak until browned.",
      "Remove the steak, then saute the onion and pepper until tender and caramelized.",
      "Preheat the oven broiler.",
      "Fill each hoagie roll with steak, peppers, and onions.",
      "Top with Swiss cheese and place on a sheet pan.",
      "Broil until the cheese has melted, then serve hot."
    ],
    nutrition: {
      calories: "590",
      protein: "35g",
      carbs: "36g",
      fat: "31g"
    }
  },
  {
    slug: "lemon-herb-salmon-bowls",
    title: "Lemon Herb Salmon Bowls",
    description: "Bright salmon bowls with roasted vegetables, fluffy rice, and a yogurt-herb drizzle.",
    category: "Meal Prep",
    cuisine: "Mediterranean",
    difficulty: "Beginner",
    dietaryTags: ["High-Protein", "Gluten-Free"],
    featured: true,
    popularScore: 87,
    addedOn: "2026-03-10",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    image: "",
    imageAlt: "",
    heroTone: "sage",
    ingredients: [
      "4 salmon fillets",
      "2 cups cooked jasmine rice",
      "1 zucchini, sliced",
      "1 pint cherry tomatoes",
      "2 tablespoons olive oil",
      "1 lemon",
      "2 tablespoons Greek yogurt",
      "Fresh dill",
      "Salt and black pepper"
    ],
    instructions: [
      "Heat the oven to 425 degrees Fahrenheit and line a sheet pan.",
      "Toss the zucchini and tomatoes with olive oil, salt, and pepper, then spread on one side of the pan.",
      "Season the salmon with lemon zest, salt, pepper, and olive oil, then place on the other side.",
      "Roast until the salmon is cooked through and the vegetables are lightly blistered, about 15 minutes.",
      "Whisk the yogurt with chopped dill and lemon juice.",
      "Divide the rice into bowls, then top with salmon, vegetables, and the yogurt sauce."
    ],
    nutrition: {
      calories: "510",
      protein: "34g",
      carbs: "32g",
      fat: "27g"
    }
  },
  {
    slug: "spicy-rigatoni-vodka",
    title: "Spicy Rigatoni Vodka",
    description: "Silky tomato cream sauce, calabrian chile heat, and a restaurant-style finish in under an hour.",
    category: "Pasta",
    cuisine: "Italian-American",
    difficulty: "Intermediate",
    dietaryTags: ["Vegetarian"],
    featured: false,
    popularScore: 85,
    addedOn: "2026-03-01",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    image: "",
    imageAlt: "",
    heroTone: "berry",
    ingredients: [
      "1 pound rigatoni",
      "2 tablespoons olive oil",
      "1 shallot, minced",
      "3 cloves garlic, minced",
      "2 tablespoons tomato paste",
      "2 teaspoons calabrian chile paste",
      "1/3 cup vodka",
      "3/4 cup heavy cream",
      "1/2 cup grated parmesan",
      "Fresh basil"
    ],
    instructions: [
      "Cook the rigatoni until just shy of al dente and reserve pasta water.",
      "Saute shallot and garlic in olive oil until fragrant.",
      "Stir in tomato paste and chile paste, cooking until darkened slightly.",
      "Add vodka and simmer for 2 minutes.",
      "Pour in the cream and parmesan, then stir until glossy.",
      "Toss in the pasta with enough pasta water to make the sauce cling.",
      "Finish with basil and more parmesan before serving."
    ],
    nutrition: {
      calories: "610",
      protein: "18g",
      carbs: "68g",
      fat: "28g"
    }
  },
  {
    slug: "honey-gochujang-chicken",
    title: "Honey Gochujang Chicken",
    description: "Sticky, spicy chicken thighs with caramelized edges and a quick cucumber salad on the side.",
    category: "Dinner",
    cuisine: "Korean-Inspired",
    difficulty: "Intermediate",
    dietaryTags: ["High-Protein", "Gluten-Free"],
    featured: false,
    popularScore: 90,
    addedOn: "2026-03-14",
    prepMinutes: 20,
    cookMinutes: 25,
    servings: 4,
    image: "",
    imageAlt: "",
    heroTone: "charcoal",
    ingredients: [
      "2 pounds boneless chicken thighs",
      "2 tablespoons gochujang",
      "2 tablespoons honey",
      "1 tablespoon soy sauce or tamari",
      "2 teaspoons sesame oil",
      "1 lime",
      "1 cucumber",
      "Scallions",
      "Cooked rice for serving"
    ],
    instructions: [
      "Whisk the gochujang, honey, soy sauce, sesame oil, and lime juice together.",
      "Coat the chicken in the sauce and marinate for at least 15 minutes.",
      "Roast or grill until the chicken is caramelized and cooked through.",
      "Slice the cucumber and toss with lime juice and a pinch of salt.",
      "Serve the chicken over rice with the cucumber salad and sliced scallions."
    ],
    nutrition: {
      calories: "470",
      protein: "33g",
      carbs: "22g",
      fat: "27g"
    }
  },
  {
    slug: "cauliflower-chickpea-tacos",
    title: "Roasted Cauliflower Chickpea Tacos",
    description: "A textured, smoky vegetarian taco with roasted cauliflower, crispy chickpeas, and a lime crema.",
    category: "Vegetarian",
    cuisine: "Mexican-Inspired",
    difficulty: "Beginner",
    dietaryTags: ["Vegetarian"],
    featured: false,
    popularScore: 76,
    addedOn: "2026-03-12",
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 4,
    image: "",
    imageAlt: "",
    heroTone: "sage",
    ingredients: [
      "1 head cauliflower, cut into florets",
      "1 can chickpeas, drained",
      "2 tablespoons olive oil",
      "1 teaspoon smoked paprika",
      "1 teaspoon cumin",
      "8 corn tortillas",
      "1/3 cup sour cream",
      "1 lime",
      "Shredded cabbage and cilantro"
    ],
    instructions: [
      "Heat the oven to 425 degrees Fahrenheit.",
      "Toss the cauliflower and chickpeas with olive oil, smoked paprika, cumin, salt, and pepper.",
      "Roast until the cauliflower is browned and the chickpeas are crisp, about 25 to 30 minutes.",
      "Mix the sour cream with lime juice and a pinch of salt.",
      "Warm the tortillas and fill them with the roasted vegetables.",
      "Finish with lime crema, shredded cabbage, and cilantro."
    ],
    nutrition: {
      calories: "390",
      protein: "12g",
      carbs: "44g",
      fat: "18g"
    }
  }
];
